- name: Update apt cache
  hosts: all
  become: true # This line enables privilege escalation
  become_user: ansible # This specifies the user to become (in this case, 'ansible')
  tasks:
    - name: Run apt update
      apt:
        update_cache: yes
