- name: Update apt cache
  hosts: all
  become: true # This line enables privilege escalation
  become_user: root # This specifies the user to become (in this case, 'root')
  become_method: sudo
  tasks:
    - name: Run apt update
      apt:
        update_cache: yes
    - name: Upgrade packages
      apt:
        upgrade: full
